# Site settings
baseURL = "http://pcarranza.github.io/meeseeks-box"
languageCode = "en-us"
title = "Meeseeks Box"
theme = "hugo-simpledoc-theme"

[blackfriday]
  angledQuotes = true
  fractions = true
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

# Top menu
# [[menu.top]]
#     name = "hugo-simpledoc-theme GitHub Repository"
#     weight = 20
#     url = "https://github.com/aerohub/hugo-simpledoc-theme"
#[[menu.top]]
#    name = "Hugo - A Fast and Flexible Website Generator"
#    weight = 10
#    url = "http://gohugo.io/"
#[[menu.top]]
#    name = "Original WPThemeDoc by Rich Tabor"
#    weight = 30
#    url = "https://github.com/richtabor/WPThemeDoc"

# Site parameters
[params]

    # Meta
    description = "You make a request. The Meeseek fulfills the request. And then it stops existing"
    author = "Pablo Carranza"
    keywords = "automation, chatops, auto-remediation, posix"
    
    # Header
    # If not set, site title and meta description will be shown.
    # You may use markdown here
    headerTitle = ""
    headerDescription = ""
    
    # Back-to-top button name
    bttButton = "go to top"
